server:
  ip: ${GUO_IP_ADDRESS}
  port: 9012

spring:
  application:
    name: cluster
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${GUO_IP_ADDRESS}:3306/jjm?characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true #You need to download MySQL and Navicat and configure the database connection information
    #The JJM part of the URL is replaced with the name of the database you created
    username: ${datasource_username} #Replace this with the database username you configured
    password: ${datasource_password} #Replace this with the database user password you configured
  redis:  #**If you run locally, you don't need to set this parameter**
    host: ${GUO_IP_ADDRESS}
    port: 6379
    password: ${redis_password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null
  servlet:
    multipart:
      enabled: true
      location: E:\jjm\tmp # 设置临时目录的路径
      max-request-size: 52128800
      max-file-size: 50MB
  mail:
     #**If you run locally, you don't need to set this parameter, delete the mail configuration**
    default-encoding: UTF-8
    port: 587
    host: smtp.qq.com
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    multipart:
      enabled: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xiangshu.test.entity


app:
  enable-interceptor: true  # true 表示启用拦截器，false 表示关闭拦截器   **If running locally, please set this parameter to false**

redis:
  enabled: true # 设置为 true 启用 Redis，为 false 禁用 Redis   **If running locally, please set this parameter to false**
